install.packages("pwt8")
library(pwt8)
data("pwt8")
data("pwt8.0")
view(pwt8.0)
View(pwt8.0)
br<-subset(pwt8.0, country=="Brazil", select = c("rgdpna","avh","xr"))
colnames(br)<- c("PIB","Trabalho","Cambio")
plot(br$PIB)
plot(br$PIB, type = "l")
write.csv(br,file = "br.csv")
rm(list = ls())
getwd()
